name: "Slack Notification Action"
description: "Send a notification message via Slack"
inputs:
  slack-token:
    description: "Slack app token"
    required: true
  slack-channel:
    description: "The Slack channel to send the message to"
    required: true
  slack-title:
    description: "The message title"
    required: false
  slack-message:
    description: "The message you want to send"
    required: true
  slack-message-fields:
    description: "A JSON string with key-values to display as fields"
    required: false
  slack-footer:
    description: "A string with key-values to display as footer"
    required: false
  slack-message-color:
    description: "The color on the vertical line of the message"
    required: false
  slack-message-id:
    description: "If you want to update a message you need to pass it's id (ts) value"
    required: false
# NOT USED YET
  slack-username:
    description: "Slack Username sending the message"
    required: false
  slack-actor:
    description: "Github username of the person who triggered the action"
    required: false
  slack-icon:
    description: "Slack message Sender icon"
    required: false
outputs:
  success:
    description: "Whether or not the message was sent"
  message_id:
    description: "The message id that was sent"
runs:
  using: node12
  main: "dist/index.js"
